version: '2'

services:
  chat-server:
    env_file:
      - ./.env2
    container_name: chat-server-sqlite
    image: chrisptang/chatgpt-slim:0.0.3
    ports:
      - 9001:5000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - HTTP_PROXY=$HTTP_PROXY
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      - GITHUB_LOGIN_CALLBACK_HOST=$GITHUB_LOGIN_CALLBACK_HOST
      - USE_SQLITE=true
    volumes:
      - ./avatar:/app/frontend/avatar
      - ./data/sqlite:/app/data/sqlite
