version: '2'

services:
  chat-server:
    container_name: chat-server
    image: chrisptang/chatgpt-slim:0.0.4
    restart: always
    ports:
      - 9000:5000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - HTTP_PROXY=$HTTP_PROXY
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      - GITHUB_LOGIN_CALLBACK_HOST=$GITHUB_LOGIN_CALLBACK_HOST
      - DEFAUL_OPENAI_MODEL=gpt-3.5-turbo-0613
      - GA_TRACKING_ID=$GA_TRACKING_ID
    volumes:
      - ./avatar:/app/frontend/avatar
    depends_on:
      - db-postgres

  db-postgres:
    container_name: db-postgres
    image: postgres:10
    restart: always
    ports:
      - "$EXPOSE_POSTGRES"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres-local
      POSTGRES_DB: chatgpt