version: '2'

services:
  db-postgres:
    container_name: db-postgres
    image: postgres:10
    ports: 
      - "5432:5432"
    volumes: 
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres-local
      POSTGRES_DB: chatgpt
      
  adminer:
    image: adminer:latest
    container_name: adminer_chatgpt
    depends_on: 
      - db-postgres
    ports:
      - 4088:8080