version: '2'

services:
  chat-server:
    container_name: chat-server-sqlite
    image: chrisptang/chatgpt-slim:0.0.1
    ports:
      - 9001:5000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - HTTP_PROXY=$HTTP_PROXY
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      - GITHUB_LOGIN_CALLBACK_HOST=localhost:9001
      - USE_SQLITE=true
    volumes:
      - ./avatar:/app/frontend/avatar
      - ./data/sqlite:/app/data/sqlite

  adminer:
    image: adminer:latest
    container_name: adminer_chatgpt_sqlite
    ports:
      - 4188:8080
