version: '2'

services:
  chat-server:
    container_name: chat-server
    image: chrisptang/chatgpt-slim:0.0.3
    restart: always
    ports:
      - 9000:5000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - HTTP_PROXY=$HTTP_PROXY
      - GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      - GITHUB_LOGIN_CALLBACK_HOST=$GITHUB_LOGIN_CALLBACK_HOST
      - DEFAUL_OPENAI_MODEL=gpt-3.5-turbo-0613
    volumes:
      - ./avatar:/app/frontend/avatar
    depends_on:
      - db-postgres

  db-postgres:
    container_name: db-postgres
    image: postgres:10
    restart: always
    # ports:
    #   - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres-local
      POSTGRES_DB: chatgpt

  adminer:
    image: adminer:latest
    container_name: adminer_chatgpt
    depends_on:
      - db-postgres
    ports:
      - 4088:8080
